import type { Metadata } from "next";
import "./globals.css";
import HeaderWrapper from "./components/hideHeader";
export const metadata: Metadata = {
  title: "Digtial Task Phone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className="">
     
<HeaderWrapper/>
        {children}
      </body>
    </html>
  );
}
