import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./components/ThemeProvider";
import HeaderWrapper from "./components/hideHeader";
export const metadata: Metadata = {
  title: "Digtial Task Phone",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <ThemeProvider>
          <HeaderWrapper />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
